### ISSUE TITLE
How did you extract required info for C1M3?

### ISSUE THREAD

**Issue by Vishwajith-K** [jtilles/coursera-introduction-embedded-systems-software-and-development-environments#3]
what flags did you make use of?
can you help me with step-by-step guide?

**Comment by jtilles** [comment]
You're going to have to give me more information than this.  All the flags for all the questions in the quiz are in the [readme](readme.md).  Read the whole thing, and if my explanations do not make sense, give me an example of how it would be more clear for you.

**Comment by jtilles** [comment]
Closing after 10 days of no comment
